//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Prueba_Web_HBR.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class tblProducto
    {
        public int idProducto { get; set; }
        public string NombreProducto { get; set; }
        public string DescripcionProducto { get; set; }
        public int idCategoria { get; set; }
        public Nullable<int> CantidadProducto { get; set; }
        public Nullable<decimal> PrecioProducto { get; set; }
    
        public virtual tblCategoria tblCategoria { get; set; }
    }
}
